Map campaign data for Screen calls
segment-integrations/analytics-ios-integration-google-analytics pull request #19
Opened 2017-06-08 19:04 UTC by tonyxiao

2017-06-08 19:11 UTC, ladanazita requested changes

2017-06-08 19:11 UTC, ladanazita commented on Pod/Classes/SEGGoogleAnalyticsIntegration.m
> +        if ([campaign[@"source"] isKindOfClass:[NSString class]]) {
Add comment/log to throw error
// Campaign source is the only required campaign field. 

Or we could consider falling back to another value in this case. [From GA](https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns) "If previous call did not set a campaign source, use the hostname as a referrer instead."

2017-06-08 19:35 UTC, tiffanyzzhu29 commented
@tonyxiao chatted with mike on this - I think we don't really see any issues with your approach, so probably defer to @ladanazita  on how you all think it's best to map it. We'll follow your lead.

2017-06-08 19:40 UTC, f2prateek requested changes
This should not be properties. There is no spec for clients sending `properties.campaign` or integrations using `properties.campaign`. `context.campaign` is spec'd https://segment.com/docs/spec/common/#context. 

By not following the spec we're creating two problems:
1.  Integrations don't know which fields the client is sending to lookup the data the need.
2. Clients don't know which fields to send.

In particular this means a user would have to instrument Segment differently just to use the GA client side integration.

Most integrations already lookup `context.campaign`.
https://github.com/segmentio/integrations/search?utf8=%E2%9C%93&q=campaign.

Analytics.js and analytics-android integrations that need this data also use `context.campaign` https://github.com/search?q=org%3Asegment-integrations+campaign&type=Code.

2017-06-08 19:56 UTC, ladanazita commented
@f2prateek our docs say otherwise:
https://segment.com/docs/spec/mobile/#campaign-related-events

Looks like these will populate through props;

```
[[SEGAnalytics sharedAnalytics] track:@"Install Attributed", properties: @{
    @"provider" : @"Tune/Kochava/Branch",
    @"campaign" : @{
        @"source" : @"Network/FB/AdWords/MoPub/Source",
        @"name" : @"Campaign Name",
        @"content" : @"Organic Content Title",
        @"ad_creative" : @"Red Hello World Ad",
        @"ad_group" : @"Red Ones"
    }
}];
```

2017-06-08 20:14 UTC, tonyxiao commented
We need to agree on whether to use context or properties. @f2prateek @ladanazita this is a blocking discussion before we can get it out.

2017-06-08 20:15 UTC, f2prateek commented
@ladanazita for the `Install Attributed` event yes you can send `properties.campaign`.  This PR is for screen calls (unrelated to `Install Attributed`).

2017-06-08 20:30 UTC, f2prateek approved these changes

2017-06-08 20:32 UTC, ladanazita approved these changes

2017-06-13 22:36 UTC, ladanazita commented
@tonyxiao Looks like Travis isn't succeeding, can you look into this?

2017-06-15 00:20 UTC, tonyxiao commented
Travis is pretty flaky. The PR actually succeeded even though that specific build failed. Just rebuilding.

2017-06-27 20:51 UTC, ladanazita commented
Added support for `track` to coincide with changes to Android, and have consistent parity between ajs, Android, and iOS for TVNZ.

![](http://g.recordit.co/8zXfRtEbeL.gif)

2017-06-27 20:58 UTC, f2prateek approved these changes

2017-06-27 21:17 UTC, ladanazita commented
Manually tested with just `campaign.source`  

`[[SEGAnalytics sharedAnalytics] track:@"Test Nulls" properties:@{} options:@{ @"context" : @{@"campaign" : @{@"source" : @"something"}} }];
`

and it populates:
![screenshot 2017-06-27 14 15 17](https://user-images.githubusercontent.com/7421111/27610445-320daf2a-5b43-11e7-98c6-1d202fe4305f.png)

Passing in no value for source logs the expected error: 
```
2017-06-27 14:14:22.231 Segment-GoogleAnalytics_Example[26759:1120101] WARNING: campaign source is a required field for GA. Omitting campaign attributes
```

2017-06-27 22:59 UTC, merged